name=AttackAnimations
version=1.0.0
author=Zahir
maintainer=Zahir 
sentence=A library for RPG-style OLED attack animations.
paragraph=Easily create projectiles and impact effects like 'Freeze' on SSD1306 OLED displays using Adafruit GFX.
category=Display
architectures=*
depends=Adafruit GFX Library, Adafruit SSD1306